version: "3"
services:
  zookeeper:
    image: 'zookeeper:latest'
    hostname: zookeeper
  producer:
    image: 'producer:latest'
    environment:
      - ZOOKEEPER_SERVER=zookeeper
  consumer:
    image: 'consumer:latest'
    environment:
      - ZOOKEEPER_SERVER=zookeeper
      - SERVER_PORT=8899
    ports:
      - 8899:8899
